// ToolTips.ts
// all the texts needed for the tooltips.

export const TOOLTIP_TEXT = {
  title:
  `KatherineMossDeveloper, a GitHub repository, contains two projects inspired by the paper, *In Situ Imaging Combined with Deep Learning for Crystallization Process Monitoring: Application to Cephalexin Production*, by Salami, H., McDonald, M. A., Bommarius, A. S., Rousseau, R. W., & Grover, M. A.

  The first project is The-Georgia-Project, which prepares the OpenCrystalData dataset, trains it using a classification model, and uploads the analysis to the Weaviate database.

  The second project is The-Midnight-Train, which pulls the analysis from the Weaviate database and presents it here.

  For the research paper, visit [In Situ Imaging Combined with Deep Learning for Crystallization Process Monitoring: Application to Cephalexin Production](https://doi.org/10.1021/acs.oprd.1c00136).

  For the Github repository, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  weaviateStatus:
  `When the Weaviate database is available, a blue dot will appear.  When it is not up-and-running, a red dot will appear.  In which case, an alternative source of data is used:  JSON files stored in this project.
  `,

  gallery:
  `These images are a curated subset from the OpenCrystalData dataset.  They were chosen using the following steps.  After applying kmeans (with PCA and designating 4 clusters), these images were chosen as representatives of the four kmeans groups:  one for CEX (in green) and three PG groups (in orange, purple, and yellow).  The images are in file name order, which happens to be (almost) the kmeans group order.

  For more on the dataset, visit [OpenCrystalData](https://kaggle.com/datasets/opencrystaldata/cephalexin-reactive-crystallization).
  `,

  force:
  `The Weaviate vector database can hold vectors, which in this project represent the features of an image learned by a model during training on the OpenCrystalData dataset.  These vectors typically have many more than three dimensions, so they are hard to quantify and visualize.

  A nearest neighbor algorithm can quantify the distance between one vector and another.  The nearest neighbor algorithm used in this project is built into the Weaviate database.

  A force directed graph is a visualization of nodes (circles) and edges (lines), where life-like properties of attraction and repulsion spread the elements out, so that they are as visible as possible.  Unlike a Cartesian plot, the meaning of a given node is defined by its relationship with the other nodes, as opposed to its X or Y coordinates.

  This force directed graph shows the image vector neighbors stored in the Weaviate database.  Nodes represent images; edges connect nearest neighbors.

  For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  slider:
  `On the left is the original image from the OpenCrystalData.  On the right is the CAM (classification activation mapping), which tells us where the A.I. model was looking at when it judged whether this image was PG.

   For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  log:
  'These messages are for debugging.',

  kmeans:
  `The circles represent the images as feature vectors generated by the model.  Each vector was reduced to 2D using PCA (principal component analysis), then assigned to four groups using Kmeans.  Each group was given a color.  The green circles are the CEX group.  The other three groups are PG.

   For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  entropy:
  `The circles represent images, each colored with its kmeans group.  CEX is green.  The other three groups are for PG.  The Y axis is entropy, a quantification of the relative complexity of the image when comparing the normalized gray-scale color values.

   For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  accordionCEX:
  `The CEX CAM Overlays Accordian component shows the middle section of all the CEX images, with a CAM (classification activation mapping) overlaid in pink.  This method is a way to show where a trained A.I. model gave the most weight to the features in the image.

   For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  accordionPG:
  `The PG CAM Overlays Accordian component shows the middle section of all the PG images, with a CAM (classification activation mapping) overlaid in pink.  This method is a way to show where a trained A.I. model gave the most weight to the features in the image.

   For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  histogram:
  `The histogram shows the count of pixels of the same color on the Y axis and the pixel color (0-255) on the X axis.

   For more on this, visit [Katherine Moss Developer](https://github.com/KatherineMossDeveloper).
  `,

  buttons:
  `The "Clear FDG" button will clear the force directed graph, but not the other graphs.

   The "Copy vector" button will save the graph below it to the clipboard, then you can paste the image into other software.  A vector image is a collection of formulas, so that one can resize the image.

   The "Copy bitmap" button will save the graph below it to the clipboard, which can also be pasted into other software.  A bitmap image is a grid of pixels, so resizing can distort the image.

   Note that some software will only accept images in one of these formats.

  `,

};

